export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_PLAY_LIST_INFO = 'SET_PLAY_LIST_INFO'
export const SET_MUSIC_URL = 'SET_MUSIC_URL'
export const SET_MUSIC_INFO = 'SET_MUSIC_INFO'
export const SET_MUSIC_INDEX = 'SET_MUSIC_INDEX'

